package org.omg.PortableServer;


/**
* org/omg/PortableServer/THREAD_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/workspace/zulu8-build-macos-aarch64/zulu-src/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, July 15, 2021 8:28:49 AM PDT
*/

public interface THREAD_POLICY_ID
{

  /**
  	 * The value representing THREAD_POLICY_ID.
  	 */
  public static final int value = (int)(16L);
}
