package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/INACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/workspace/zulu8-build-macos-aarch64/zulu-src/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, July 15, 2021 8:28:48 AM PDT
*/

public interface INACTIVE
{

  /** Object adapter state that causes all requests to be discarded.
     * This state indicates that the adapter is shutting down.
     */
  public static final short value = (short)(3);
}
